### ISSUE TITLE
pip-sync fails with a local editable

### ISSUE THREAD

**Issue by gsakkis** [nvie/pip-tools#223] opened 2015-11-03 12:29 UTC
Similar to #176 (which should have been marked as resolved) but now pip-sync fails on latest release (1.1.6):

```
  File "/tmp/venv/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/tmp/venv/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/venv/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/tmp/venv/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/venv/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/tmp/venv/local/lib/python2.7/site-packages/piptools/scripts/sync.py", line 51, in cli
    requirements = sync.merge(requirements, ignore_conflicts=force)
  File "/tmp/venv/local/lib/python2.7/site-packages/piptools/sync.py", line 74, in merge
    key = ireq.req.key
AttributeError: 'NoneType' object has no attribute 'key'
```

**Comment by nvie** [comment] 2016-04-20 20:27
Closing this. Dupe of #325.

**Closed by nvie** 2016-04-20 20:27 UTC
