### ISSUE TITLE
pip-compile: Could not find a version that matches Django<1.8.0,==1.8.2,>=1.2,>=1.2.4,>=1.4.0,>=1.4.2,>=1.8

### ISSUE THREAD

**Issue by d33tah** [nvie/pip-tools#309] opened 2016-01-27 13:20 UTC
```
(virtualenv)[ACL][14:19:27][/tmp]$ pip-compile requirements.in 
/home/d/virtualenv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/d/virtualenv/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Could not find a version that matches Django<1.8.0,==1.8.2,>=1.2,>=1.2.4,>=1.4.0,>=1.4.2,>=1.8
Tried: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.12, 1.6, 1.6, 1.6.1, 1.6.1, 1.6.2, 1.6.2, 1.6.3, 1.6.3, 1.6.4, 1.6.4, 1.6.5, 1.6.5, 1.6.6, 1.6.6, 1.6.7, 1.6.7, 1.6.8, 1.6.8, 1.6.9, 1.6.9, 1.6.10, 1.6.10, 1.6.11, 1.6.11, 1.7, 1.7, 1.7.1, 1.7.1, 1.7.2, 1.7.2, 1.7.3, 1.7.3, 1.7.4, 1.7.4, 1.7.5, 1.7.5, 1.7.6, 1.7.6, 1.7.7, 1.7.7, 1.7.8, 1.7.8, 1.7.9, 1.7.9, 1.7.10, 1.7.10, 1.7.11, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8, 1.8.1, 1.8.1, 1.8.2, 1.8.2, 1.8.3, 1.8.3, 1.8.4, 1.8.4, 1.8.5, 1.8.5, 1.8.6, 1.8.6, 1.8.7, 1.8.7, 1.8.8, 1.8.8, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9, 1.9.1, 1.9.1      
(virtualenv)[ACL][14:19:33][/tmp][2] $ cat requirements.in 
amqp==1.4.7
anyjson==0.3.3
arrow==0.7.0
bcrypt==2.0.0
bdateutil==0.1
bicyclerepair==0.9
billiard==3.3.0.21
bpgsql==2.0a2
celery==3.1.19
cffi==1.3.1
characteristic==14.3.0
CherryPy==4.0.0
click==6.2
colorama==0.3.3
configobj==5.0.6
coverage==4.0.3
cryptography==1.1.1
csvkit==0.9.1
curve25519-donna==1.3
cv2==1.0
Cython==0.23.4
dbf==0.94.3
Django==1.8.2
django-admin-bootstrapped==2.5.6
django-bootstrap3==6.2.2
django-celery==3.1.17
django-celery-transactions==0.3.5
django-debug-toolbar==1.3.2
django-kombu==0.9.4
django-mass-edit==2.4
django-nested-inline==0.3.5
django-readonly==0.1.2
django-tables2==1.0.4
django-transaction-barrier==0.3
docopt==0.6.2
docutils==0.12
enum34==1.0.4
first==2.0.1
Flask==0.10.1
Flask-MakoTemplates==0.2
funcsigs==0.4
functools32==3.2.3.post2
fuse-python==0.2
GeoIP==1.3.2
geoip2==2.2.0
git-up==1.3.0
gitdb==0.6.4
GitPython==1.0.0
hkdf==0.0.1
holidays==0.3.1
humanize==0.5.1
idna==2.0
interpy==1.1
ipaddr==2.1.11
ipaddress==1.0.6
IPy==0.83
ipython==3.2.0
itsdangerous==0.24
jdcal==1.2
Jinja2==2.8
jpath==1.5
kombu==3.0.29
lxml==3.4.4
Mako==1.0.3
MarkupSafe==0.23
maxminddb==1.2.0
mechanize==0.2.5
mock==1.0.0
newpy==1.1.14
npyscreen==4.9.1
numpy==1.9.2
ooniprobe==1.3.1
openpyxl==2.2.0b1
Parsley==1.2
PasteDeploy==1.5.2
pbr==1.8.1
pgcli==0.18.0
phpsh==1.3.5
Pillow==2.9.0
pip-tools==1.5
prompt-toolkit==0.42
psutil==3.0.1
psycopg2==2.6.1
psycopg2cffi==2.7.2
pyasn1==0.1.9
pyasn1-modules==0.0.5
pycparser==2.14
pycrypto==2.6.1
pydumbnet==1.12.1
pyelftools==0.23
pygame==1.9.2a0
Pygments==2.0.2
PyGreSQL==4.2
PyNaCl==0.3.0
PyOpenGL==3.1.0
pyOpenSSL==0.14
pypcap==1.1.1
pyramid==1.6
pyramid-mako==1.0.2
pyregdom==0.4.post4
python-dateutil==2.2
python-memcached==1.53
pytz==2015.7
PyYAML==3.11
pyzmq==15.0.0
repoze.lru==0.6
requests==2.7.0
scapy-real==2.2.0.dev0
selenium==2.47.3
service-identity==14.0.0
six==1.9.0
smmap==0.9.0
SQLAlchemy==1.0.11
sqlparse==0.1.16
stem==1.3.0
tblib==1.1.0
termcolor==1.1.0
translationstring==1.3
Twisted==14.0.0
txsocksx==1.13.0.3
txtorcon==0.13.0
venusian==1.0
wcwidth==0.1.4
WebOb==1.5.1
Werkzeug==0.10.4
xlrd==0.9.4
yolk==0.4.3
youtube-dl==2015.12.31
zope.deprecation==4.1.2
zope.interface==4.1.2
```

**Comment by jonafato** [comment] 2016-01-29 06:19
This seems like correct behavior. Your `requirements.in` specifies `Django==1.8.2`, but `django-transaction-barrier==0.3` [requires](https://github.com/godaddy/django_transaction_barrier/blob/22bf2607a515174e4d5571a88e599d36d5cd04d6/setup.py#L25) `Django>=1.4.0,<1.8.0`. No version could satisfy both `==1.8.2` and `<1.8.0`, so the compilation can't proceed.

**Comment by nvie** [comment] 2016-01-29 07:24
Agreed. This is as intended. I do agree the messaging could improve. Closing this in favor of #220.

**Closed by nvie** 2016-01-29 07:24 UTC
