### ISSUE TITLE
[Windows] FileExistsError using pip-compile

### ISSUE THREAD

**Issue by floqqi** [nvie/pip-tools#351] opened 2016-04-28 10:43 UTC
Using `pip-compile requirements.in --output-file=requirements.txt` fails at overriding if the output-file already exists (using Windows, OS X works fine).

##### Steps to replicate

1. `pip-compile requirements.in --output-file=requirements.txt` (when `requirements.txt` doesn't exist)
2. run the command above again (`requirements.txt` now exists)

##### Expected result (by step)

1. create `requirements.txt`
2. override existing `requirements.txt`

##### Actual result (by step)

1. works fine
2. following error is raised (in German):

    ```
    FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: 'requirements.txt.part' -> 'C:\\Users\\floqqi\\Projects\\test\\requirements.txt'
    ```

    which roughly translates to `Can not create file, if it is already existing: 'requirements.txt.part' -> ...`

**Comment by nvie** [comment] 2016-04-28 18:10
Thanks for the report. Are you on the latest version of pip-tools with this? The reason I'm asking is that I'm pretty sure this has been addressed in an earlier version, so this would be a regression.

The code that's failing is vendored into pip-tools from [boltons](https://github.com/mahmoud/boltons), a pretty sweet library maintained by Mahmoud Hashemi. 

I believe this was the issue back then, which was fixed: https://github.com/mahmoud/boltons/issues/45. Assuming you're on the latest version of pip-tools, perhaps we can see if @mahmoud has any idea what could be causing this?

**Comment by floqqi** [comment] 2016-04-28 18:38
Yes, I'm using the latest version available on PyPi (on Windows 7).

**Comment by davidovich** [comment] 2016-04-28 19:07
I had tried to make a [PR](https://github.com/nvie/pip-tools/pull/322) on this very issue, and @nvie kindly pointed me to report upstream, which [I did](https://github.com/mahmoud/boltons/issues/60). Is there an automatic vendoring procedure that would have brought that in pip-tools ?

**Comment by nvie** [comment] 2016-04-28 19:19
Ugh! So this _was_ fixed, and I remembered this, but I did not vendor this back in? That's pretty stupid of me :) I'll have a look later, probably tomorrow. Sorry about that :)

**Comment by mahmoud** [comment] 2016-04-29 17:49
Lemme know if there's anything I can do to help! I've only gotten compliments on the new AtomicFileSaver Windows support. Proud to say I'm pretty sure it's the most complete pure-Python solution in the FOSS world! :)

**Comment by nvie** [comment] 2016-05-02 07:12
This is now fixed and released as 1.6.3, see https://pypi.python.org/pypi/pip-tools. Thanks for reporting @floqqi and thanks for fixing @mahmoud!

**Closed by nvie** 2016-05-02 07:12 UTC

**Comment by floqqi** [comment] 2016-05-02 10:52
@nvie I'm encountering some odd behavior using `pip-compile` now.

`pip-compile.exe requirements.in --output-file=requirements.txt` doesn't override `requirements.txt`. A file named `requirements.txt.bak` is now created.

**Comment by nvie** [comment] 2016-05-02 10:55
Hmm. @mahmoud any idea what could be happening here? Are you running this for a user that's allowed to overwrite requirements.txt? Any error when you run this?

**Comment by floqqi** [comment] 2016-05-02 10:59
My user is allowed to override `requirements.txt`. This happens even when running cmd as Administrator. No error happens, just the regular output.

**Comment by nvie** [comment] 2016-05-02 11:00
Does it fail silently, or do you see a stack trace? Please share if so.

**Comment by floqqi** [comment] 2016-05-02 11:26
No error is raised. Just regular output as if anything is okay:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#

amqp==1.4.9               # via kombu
aniso8601==1.1.0          # via flask-restful
anyjson==0.3.3            # via kombu
cached-property==1.3.0
cx-oracle==5.2.1
dicttoxml==1.6.6
eventlet==0.18.4          # via nameko
flask-marshmallow==0.6.2
flask-restful==0.3.5
flask-script==2.0.5
flask-sqlalchemy==2.1
flask==0.10.1
greenlet==0.4.9           # via eventlet
itsdangerous==0.24        # via flask
Jinja2==2.8               # via flask
kombu==3.0.35             # via nameko
ldap3==1.2.2
MarkupSafe==0.23          # via jinja2
marshmallow-sqlalchemy==0.8.1
marshmallow==2.7.2
mock==2.0.0               # via nameko
nameko==2.3.0
path.py==8.2.1            # via nameko
pbr==1.9.1                # via mock
pyasn1==0.1.9             # via ldap3
pymysql==0.7.2
pyodbc==3.0.10
python-dateutil==2.5.3    # via aniso8601
pytz==2016.4              # via flask-restful
pyyaml==3.11              # via nameko
requests==2.9.1           # via nameko
six==1.10.0               # via flask-marshmallow, flask-restful, mock, nameko, python-dateutil
sqlalchemy==1.0.12
webargs==1.3.2
werkzeug==0.11.9          # via flask, nameko
```

`requirements.txt.bak` has this ^ content.

**Comment by floqqi** [comment] 2016-05-02 11:29
Okay, just tested it with pinning a version in my `requirements.in`-file. `requirements.txt` gets overriden, but `requirements.txt.bak` won't be deleted.

Thought it doesn't override something because there was nothing to override, sorry.

**Comment by nvie** [comment] 2016-05-02 15:03
If you remove the `*.bak` file, does it keep getting back? If so, that's a bug. If not, can we close this?

**Comment by mahmoud** [comment] 2016-05-02 16:56
Hey! I'm back. I'll pull up Windows and see if I can reproduce this. What version of Windows are we on? (I've been testing on 7.)

**Comment by mahmoud** [comment] 2016-05-02 17:33
Just tried out 1.6.3 on my Windows 7 machine. The behavior is as follows:

When the file does not already exist, everything is created fine. When the file does exist, I see it replaced fine as well. This could be confusion related to the backup file part of the Windows [ReplaceFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365512%28v=vs.85%29.aspx) API. I was under the impression that it would remove it if the swap was successful, but it seems to be a higher-level, non-temporary backup, similar to emacs's `xyz.txt~`-style backups.

So, new version of boltons tonight, with the .bak file removed. I'll leave a comment here as soon as it's ready.

**Comment by nvie** [comment] 2016-05-02 22:50
Sweet. Once it's released, I'll roll a new version of pip-tools right after.

**Comment by mahmoud** [comment] 2016-05-03 08:38
All ready to go! .bak files should be a thing of the past. :)

**Comment by nvie** [comment] 2016-05-03 08:55
I just pushed out pip-tools 1.6.4 that includes this fix, see https://pypi.python.org/pypi/pip-tools. Thanks for the contributions!

**Comment by floqqi** [comment] 2016-05-03 10:13
@nvie: Now it works as expected, thank you!
