### ISSUE TITLE
pip-compile fails with a local editable

### ISSUE THREAD

**Issue by dstufft** [nvie/pip-tools#176] opened 2015-07-01 23:44 UTC
I have a project which is packaged, and I would like to take a list of dependencies from inside of the ``setup.py`` for that project, and compile it down to a list with ``pip-compile``. Since it only supports ``requirements.in`` I went ahead and created one that looked like:

```
-e .
```

This resulted in an exception like:

```
Traceback (most recent call last):
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/bin/pip-compile", line 9, in <module>
    load_entry_point('pip-tools==1.0.dev1', 'console_scripts', 'pip-compile')()
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/piptools/scripts/compile.py", line 81, in cli
    results = resolver.resolve()
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/piptools/resolver.py", line 71, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/piptools/resolver.py", line 142, in _resolve_one_round
    constraints = sorted(self.constraints, key=lambda ireq: ireq.req.key)
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/piptools/resolver.py", line 42, in constraints
    self.their_constraints)))
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/piptools/resolver.py", line 115, in _group_constraints
    for _, ireqs in full_groupby(constraints, key=lambda ireq: ireq.req.key):
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/piptools/utils.py", line 79, in full_groupby
    return groupby(sorted(iterable, key=key), key=key)
  File "/Users/dstufft/.virtualenvs/tmp-63439e9bc9e5262/lib/python3.4/site-packages/piptools/resolver.py", line 115, in <lambda>
    for _, ireqs in full_groupby(constraints, key=lambda ireq: ireq.req.key):
AttributeError: 'NoneType' object has no attribute 'key'
```

What I'd really like, is a way to do something like ``pip-compile .`` without having to write a .in file, and have it resolve the dependencies of the package in the current directory, but at the very least, ``-e .`` should work.

**Comment by nvie** [comment] 2016-04-20 20:27
Closing this. Dupe of #325.

**Closed by nvie** 2016-04-20 20:27 UTC
