### ISSUE TITLE
pip-compile fails when scipy==0.9.0 is in requirements.in

### ISSUE THREAD

**Issue by flavianh** [nvie/pip-tools#279] opened 2015-12-27 17:26 UTC
Here is the best traceback I've got:
```bash
scipy==0.9.0 not in cache, need to check index
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/base-requirements/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 141, in cli
    results = resolver.resolve()
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/piptools/resolver.py", line 78, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/piptools/resolver.py", line 160, in _resolve_one_round
    for best_match in best_matches
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/piptools/resolver.py", line 161, in <genexpr>
    for dep in self._iter_dependencies(best_match))
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/piptools/resolver.py", line 230, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 129, in get_dependencies
    dependencies = reqset._prepare_file(self.finder, ireq)
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/pip/req/req_set.py", line 505, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/pip/req/req_set.py", line 123, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/pip/req/req_install.py", line 410, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/vagrant/.virtualenvs/base-requirements/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 733, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpdjlH0kbuild/scipy
```

**pip-tools version**: 1.4.2

I tried to download scipy myself at the right version, extract it, and run `python setup.py egg_info`, which worked fine (I expected a dependency issue).

I reverted back to pip-tools 1.2.0, issues the same command and then it worked and the requirements.txt file was generated. I wanted to pinpoint exactly where the regression was, but when I switched back to version 1.4.2, the problem was gone, even when I added the `-r` option.

**Comment by nvie** [comment] 2016-04-25 22:50
Closing, duplicate of #228.

**Closed by nvie** 2016-04-25 22:50 UTC
