### ISSUE TITLE
pip-dump not splitting requirements correctly

### ISSUE THREAD

**Issue by lajarre** [nvie/pip-tools#133] opened 2015-02-18 18:58 UTC
pip 6.0.8

pip-tools==0.3.5

I have a requirements.txt and a dev-requirements.txt (with a proper distribution of packages between the two).

`pip-dump` gets everything from `pip freeze` written to both files.

This happens after going to Python 2.7.9 and doing `pip install --upgrade pip`

**Comment by Surgo** [comment] 2015-03-29 13:37
:(

**Comment by mlew** [comment] 2015-04-05 16:24
Same thing is happening for me

**Comment by maniqui** [comment] 2015-04-10 02:37
^^ To me too.

**Comment by mlew** [comment] 2015-04-10 17:20
This appears to be fixed on master, we just need a new version to be cut and released to PyPI.

**Comment by nvie** [comment] 2015-04-11 07:00
I've released the current master branch as 0.3.6 now. Thanks for the work!

**Comment by maniqui** [comment] 2015-04-13 20:18
hi @nvie 
I've updated to latest release (v0.3.6).
The first time I ran `pip-dump` after upgrade, it emptied both of my requirements files (`requirements/common.txt` & `requirements/dev.txt). 
I was confused.
So, just after that (and without resetting my requirements files to a good state), I ran `pip-dump` for a second time. Now, my `requirements/common.txt` file got populated with all the requirements, but the `requirements/dev.txt` file remained empty.
Then, after that, I fixed the files manually, by deleting dev dependencies from `common.txt` and adding them back to `dev.txt`. 
So far, so good, and it was the time for a final test: I've re-run `pip-dump`, to see if it would mangle my files again, or if it would do nothing at all (which was expected, as both my `common.txt` and `dev.txt` were now manually fixed and up-to-date). Thankfully, `pip-dump` did nothing, probably because there was nothing to do, as the requirement files were up-to-date.

Of course, there is still initial the issue of `pip-dump` emptying my requirement files on first run. I was able to reproduce it several times, by reverting the contents back.

So, my guess (and maybe it's something you could try to do to reproduce my issue) is that `pip-dump` might be failing (by emptying the requirements files) when they are outdated.
The easy test would be to have an outdated requirements file and run `pip-dump`.

Let me know if you need more info.

**Comment by nvie** [comment] 2015-07-21 11:50
`pip-dump` is gone with the release of 1.0: http://nvie.com/posts/pip-tools-10-released/

**Closed by nvie** 2015-07-21 11:50 UTC
Labels: old (dump+review)
